version: "2.4"

services:
  # alpha:
  #   image: elixir:latest
  #   volumes:
  #     - ./alpha:/app
  #   container_name: alpha
  #   working_dir: /app
  #   entrypoint:
  #     [
  #       "/bin/sh",
  #       "-c",
  #       "cd /app && mix deps.get && iex --sname alpha@localhost -S mix",
  #     ]
  # beta:
  #   image: elixir:latest
  #   volumes:
  #     - ./beta:/app
  #   container_name: beta
  #   working_dir: /app
  #   entrypoint:
  #     [
  #       "/bin/sh",
  #       "-c",
  #       "cd /app && mix deps.get && iex --sname beta@localhost -S mix",
  #     ]
  # charlie:
  #   image: elixir:latest
  #   volumes:
  #     - ./charlie:/app
  #   container_name: charlie
  #   working_dir: /app
  #   entrypoint:
  #     [
  #       "/bin/sh",
  #       "-c",
  #       "cd /app && mix deps.get && iex --sname charlie@localhost -S mix",
  #     ]
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
      - MYSQL_HOST=mysql
    ports:
      - 9411:9411
  # elasticsearch:
  #   image: elasticsearch:7.9.2
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  # kibana:
  #   depends_on:
  #     - elasticsearch
  #   image: docker.elastic.co/kibana/kibana:7.9.2
  #   container_name: kibana
  #   ports:
  #     - 5601:5601
  #   restart: always
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    container_name: elasticsearch
    volumes:
      - elasticsearch-data-new:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.4.0
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - 5601:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  elasticsearch-data-new:
    driver: local
  kibana-data:
    driver: local
